"""SQLAlchemy ORM models.

Read-only models map to existing CRM tables (never INSERT/UPDATE).
Read-write CX_ models map to the Salezilla extension tables.
"""

from datetime import datetime

from sqlalchemy import Boolean, DateTime, FetchedValue, Integer, String, Text, Unicode, UnicodeText
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


# ═════════════════════════════════════════════════════════════════════════════
# READ-ONLY — Existing CRM tables
# ═════════════════════════════════════════════════════════════════════════════


class User(Base):
    """Maps to the existing `users` table. Read-only."""

    __tablename__ = "users"

    user_id: Mapped[str] = mapped_column("User Id", String(32), primary_key=True)
    zuid: Mapped[str | None] = mapped_column("ZUID", Unicode(16), nullable=True)
    email: Mapped[str] = mapped_column("Email", Unicode(128), nullable=False)
    name: Mapped[str] = mapped_column("Name", Unicode(128), nullable=False)
    first_name: Mapped[str | None] = mapped_column("FirstName", Unicode(128), nullable=True)
    last_name: Mapped[str | None] = mapped_column("LastName", Unicode(128), nullable=True)
    role: Mapped[str | None] = mapped_column("Role", Unicode(128), nullable=True)
    profile: Mapped[str | None] = mapped_column("Profile", Unicode(32), nullable=True)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False)
    user_status: Mapped[str] = mapped_column("User Status", String(8), nullable=False)
    reporting_to: Mapped[str | None] = mapped_column("reporting_to", Unicode(200), nullable=True)


class Account(Base):
    """Maps to the existing `Accounts` table. Read-only."""

    __tablename__ = "Accounts"

    # DB-side autogenerated (IDENTITY or DEFAULT). Do not set on INSERT — the
    # server assigns it; SQLAlchemy fetches the generated value via OUTPUT INSERTED.
    account_id: Mapped[str] = mapped_column("Account Id", String(32), primary_key=True, server_default=FetchedValue())
    account_owner_id: Mapped[str | None] = mapped_column("Account Owner Id", String(32), nullable=True)
    account_name: Mapped[str | None] = mapped_column("Account Name", String(256), nullable=True)
    industry: Mapped[str | None] = mapped_column("Industry", String(64), nullable=True)
    website: Mapped[str | None] = mapped_column("Website", String(256), nullable=True)
    employees: Mapped[int | None] = mapped_column("Employees", Integer, nullable=True)
    annual_revenue: Mapped[float | None] = mapped_column("Annual Revenue", nullable=True)
    phone: Mapped[str | None] = mapped_column("Phone", String(32), nullable=True)
    billing_street: Mapped[str | None] = mapped_column("Billing Street", String(512), nullable=True)
    billing_city: Mapped[str | None] = mapped_column("Billing City", String(256), nullable=True)
    billing_state: Mapped[str | None] = mapped_column("Billing State", String(256), nullable=True)
    billing_code: Mapped[str | None] = mapped_column("Billing Code", String(32), nullable=True)
    billing_country: Mapped[str | None] = mapped_column("Billing Country", String(256), nullable=True)
    country_fws: Mapped[str | None] = mapped_column("Country FWS", String(256), nullable=True)
    description: Mapped[str | None] = mapped_column("Description", Text, nullable=True)
    rating: Mapped[str | None] = mapped_column("Rating", String(8), nullable=True)
    account_type: Mapped[str | None] = mapped_column("Account Type", String(8), nullable=True)
    created_by: Mapped[str | None] = mapped_column("Created By", String(32), nullable=True)
    modified_by: Mapped[str | None] = mapped_column("Modified By", String(32), nullable=True)
    created_time: Mapped[datetime | None] = mapped_column("Created Time", DateTime, nullable=True)
    modified_time: Mapped[datetime | None] = mapped_column("Modified Time", DateTime, nullable=True)


class Contact(Base):
    """Maps to the existing `Contacts` table. Read-only."""

    __tablename__ = "Contacts"

    # DB-side autogenerated — do not set on INSERT (see Account.account_id note).
    contact_id: Mapped[str] = mapped_column("Contact Id", String(32), primary_key=True, server_default=FetchedValue())
    contact_owner_id: Mapped[str | None] = mapped_column("Contact Owner Id", String(32), nullable=True)
    first_name: Mapped[str | None] = mapped_column("First Name", String(128), nullable=True)
    last_name: Mapped[str | None] = mapped_column("Last Name", String(128), nullable=True)
    full_name: Mapped[str | None] = mapped_column("Full Name", String(128), nullable=True)
    title: Mapped[str | None] = mapped_column("Title", String(128), nullable=True)
    email: Mapped[str | None] = mapped_column("Email", String(256), nullable=True)
    phone: Mapped[str | None] = mapped_column("Phone", String(32), nullable=True)
    mobile: Mapped[str | None] = mapped_column("Mobile", String(32), nullable=True)
    account_id: Mapped[str | None] = mapped_column("Account Id", String(32), nullable=True)
    lead_source: Mapped[str | None] = mapped_column("Lead Source", String(32), nullable=True)
    department: Mapped[str | None] = mapped_column("Department", String(256), nullable=True)
    created_by: Mapped[str | None] = mapped_column("Created By", String(32), nullable=True)
    modified_by: Mapped[str | None] = mapped_column("Modified By", String(32), nullable=True)
    created_time: Mapped[datetime | None] = mapped_column("Created Time", DateTime, nullable=True)
    modified_time: Mapped[datetime | None] = mapped_column("Modified Time", DateTime, nullable=True)


class Potential(Base):
    """Maps to the existing `Potentials` table. Read-only."""

    __tablename__ = "Potentials"

    # DB-side autogenerated — do not set on INSERT (see Account.account_id note).
    potential_id: Mapped[str] = mapped_column("Potential Id", String(32), primary_key=True, server_default=FetchedValue())
    # 7-digit business identifier, also DB-assigned. Fetched via OUTPUT INSERTED
    # so callers can read it immediately after session.flush()/.commit().
    potential_number: Mapped[str | None] = mapped_column("Potential Number", String(32), nullable=True, server_default=FetchedValue())
    potential_owner_id: Mapped[str | None] = mapped_column("Potential Owner Id", String(32), nullable=True)
    potential_owner_name: Mapped[str | None] = mapped_column("Potential Owner Name", Unicode(128), nullable=True)
    potential_name: Mapped[str | None] = mapped_column("Potential Name", String(256), nullable=True)
    amount: Mapped[float | None] = mapped_column("Amount", nullable=True)
    stage: Mapped[str | None] = mapped_column("Stage", String(64), nullable=True)
    probability: Mapped[float | None] = mapped_column("Probability (%)", nullable=True)
    closing_date: Mapped[datetime | None] = mapped_column("Closing Date", DateTime, nullable=True)
    account_id: Mapped[str | None] = mapped_column("Account Id", String(32), nullable=True)
    contact_id: Mapped[str | None] = mapped_column("Contact Id", String(32), nullable=True)
    service: Mapped[str | None] = mapped_column("Service", String(64), nullable=True)
    sub_service: Mapped[str | None] = mapped_column("Sub Service", String(64), nullable=True)
    lead_source: Mapped[str | None] = mapped_column("Lead Source", String(32), nullable=True)
    form_url: Mapped[str | None] = mapped_column("Form URL", String(256), nullable=True)
    next_step: Mapped[str | None] = mapped_column("Next Step", String(64), nullable=True)
    deal_size: Mapped[str | None] = mapped_column("Deal Size", String(32), nullable=True)
    description: Mapped[str | None] = mapped_column("Description", Text, nullable=True)
    type: Mapped[str | None] = mapped_column("Type", String(32), nullable=True)
    potential2close: Mapped[int | None] = mapped_column("Potential2Close", Integer, nullable=True)
    hot_potential: Mapped[str | None] = mapped_column("Hot_Potential", String(16), nullable=True)
    not_an_inquiry_reason: Mapped[str | None] = mapped_column("Not_an_Inquiry_Reas", UnicodeText, nullable=True)
    disqualify_reason: Mapped[str | None] = mapped_column("Reason to Disqualify", UnicodeText, nullable=True)
    created_time: Mapped[datetime | None] = mapped_column("Created Time", DateTime, nullable=True)
    modified_time: Mapped[datetime | None] = mapped_column("Modified Time", DateTime, nullable=True)


# ═════════════════════════════════════════════════════════════════════════════
# READ-WRITE — CX_ extension tables
# ═════════════════════════════════════════════════════════════════════════════


class CXUserToken(Base):
    """Microsoft OAuth tokens per user."""

    __tablename__ = "CX_UserTokens"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column("UserId", String(32), nullable=False)
    provider: Mapped[str] = mapped_column("Provider", String(32), nullable=False, default="microsoft")
    access_token: Mapped[str | None] = mapped_column("AccessToken", UnicodeText, nullable=True)
    refresh_token: Mapped[str | None] = mapped_column("RefreshToken", UnicodeText, nullable=True)
    ms_email: Mapped[str | None] = mapped_column("MSEmail", Unicode(256), nullable=True)
    token_expiry: Mapped[datetime | None] = mapped_column("TokenExpiry", DateTime, nullable=True)
    calendar_sync_cursor: Mapped[str | None] = mapped_column("CalendarSyncCursor", String(256), nullable=True)
    email_signature: Mapped[str | None] = mapped_column("EmailSignature", UnicodeText, nullable=True)
    working_hours_start: Mapped[str | None] = mapped_column("WorkingHoursStart", String(5), nullable=True)  # "09:00"
    working_hours_end: Mapped[str | None] = mapped_column("WorkingHoursEnd", String(5), nullable=True)      # "18:00"
    timezone: Mapped[str | None] = mapped_column("Timezone", String(64), nullable=True)                      # IANA, e.g. "Asia/Kolkata"
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXOTPCode(Base):
    """OTP codes for email-based login."""

    __tablename__ = "CX_OTPCodes"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column("UserId", String(32), nullable=False)
    code: Mapped[str] = mapped_column("Code", String(8), nullable=False)
    expires_at: Mapped[datetime] = mapped_column("ExpiresAt", DateTime, nullable=False)
    is_used: Mapped[bool] = mapped_column("IsUsed", Boolean, nullable=False, default=False)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXQueueItem(Base):
    """Daily action queue items linked to Potentials."""

    __tablename__ = "CX_QueueItems"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    contact_id: Mapped[str | None] = mapped_column("ContactId", String(32), nullable=True)
    account_id: Mapped[str | None] = mapped_column("AccountId", String(32), nullable=True)
    folder_type: Mapped[str] = mapped_column("FolderType", String(32), nullable=False)
    title: Mapped[str] = mapped_column("Title", Unicode(256), nullable=False)
    subtitle: Mapped[str | None] = mapped_column("Subtitle", Unicode(256), nullable=True)
    preview: Mapped[str | None] = mapped_column("Preview", UnicodeText, nullable=True)
    time_label: Mapped[str | None] = mapped_column("TimeLabel", String(32), nullable=True)
    priority: Mapped[str | None] = mapped_column("Priority", String(16), nullable=True)
    status: Mapped[str] = mapped_column("Status", String(16), nullable=False, default="pending")
    assigned_to_user_id: Mapped[str | None] = mapped_column("AssignedToUserId", String(32), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXAgentInsight(Base):
    """Cached AI agent results per Potential.

    For meeting briefs: ms_event_id is set to the MS Graph event id, so the
    same potential can have one brief per scheduled meeting. For all other
    agents, ms_event_id is NULL.
    """

    __tablename__ = "CX_AgentInsights"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    agent_type: Mapped[str] = mapped_column("AgentType", String(64), nullable=False)
    ms_event_id: Mapped[str | None] = mapped_column("MSEventId", String(256), nullable=True)
    agent_id: Mapped[str | None] = mapped_column("AgentId", String(64), nullable=True)
    agent_name: Mapped[str | None] = mapped_column("AgentName", Unicode(128), nullable=True)
    content: Mapped[str | None] = mapped_column("Content", UnicodeText, nullable=True)
    content_type: Mapped[str | None] = mapped_column("ContentType", String(16), nullable=True)
    status: Mapped[str] = mapped_column("Status", String(16), nullable=False, default="pending")
    execution_id: Mapped[str | None] = mapped_column("ExecutionId", String(64), nullable=True)
    run_id: Mapped[str | None] = mapped_column("RunId", String(64), nullable=True)
    triggered_by: Mapped[str | None] = mapped_column("TriggeredBy", String(32), nullable=True)
    triggered_at: Mapped[datetime | None] = mapped_column("TriggeredAt", DateTime, nullable=True)
    error_message: Mapped[str | None] = mapped_column("ErrorMessage", UnicodeText, nullable=True)
    requested_time: Mapped[datetime | None] = mapped_column("RequestedTime", DateTime, nullable=True)
    completed_time: Mapped[datetime | None] = mapped_column("CompletedTime", DateTime, nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXAgentTypeConfig(Base):
    """Agent type registry — maps agent system IDs to Salezilla tabs."""

    __tablename__ = "CX_AgentTypeConfig"

    # Composite PK: (agent_id, trigger_category). Same agent can serve multiple
    # categories (e.g. attachment agent for both followUp and followUpInactive).
    agent_id: Mapped[str] = mapped_column("AgentId", String(64), primary_key=True)
    trigger_category: Mapped[str] = mapped_column("TriggerCategory", String(32), primary_key=True)
    agent_name: Mapped[str] = mapped_column("AgentName", Unicode(128), nullable=False)
    tab_type: Mapped[str] = mapped_column("TabType", String(32), nullable=False)
    content_type: Mapped[str] = mapped_column("ContentType", String(16), nullable=False, default="markdown")
    sort_order: Mapped[int] = mapped_column("SortOrder", Integer, nullable=False, default=0)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)


class CXEmailDraft(Base):
    """AI-generated email drafts."""

    __tablename__ = "CX_EmailDrafts"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    queue_item_id: Mapped[int | None] = mapped_column("QueueItemId", Integer, nullable=True)
    to_email: Mapped[str | None] = mapped_column("ToEmail", String(256), nullable=True)
    subject: Mapped[str | None] = mapped_column("Subject", Unicode(512), nullable=True)
    body: Mapped[str | None] = mapped_column("Body", UnicodeText, nullable=True)
    status: Mapped[str] = mapped_column("Status", String(16), nullable=False, default="draft")
    created_by_user_id: Mapped[str | None] = mapped_column("CreatedByUserId", String(32), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXUserEmailDraft(Base):
    """User-composed email drafts (Email tab composer)."""

    __tablename__ = "CX_UserEmailDrafts"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    to_email: Mapped[str | None] = mapped_column("ToEmail", Unicode(512), nullable=True)
    to_name: Mapped[str | None] = mapped_column("ToName", Unicode(256), nullable=True)
    cc_emails: Mapped[str | None] = mapped_column("CcEmails", UnicodeText, nullable=True)
    bcc_emails: Mapped[str | None] = mapped_column("BccEmails", UnicodeText, nullable=True)
    subject: Mapped[str | None] = mapped_column("Subject", Unicode(512), nullable=True)
    body: Mapped[str | None] = mapped_column("Body", UnicodeText, nullable=True)
    reply_to_thread_id: Mapped[str | None] = mapped_column("ReplyToThreadId", Unicode(512), nullable=True)
    reply_to_message_id: Mapped[str | None] = mapped_column("ReplyToMessageId", Unicode(512), nullable=True)
    status: Mapped[str] = mapped_column("Status", String(16), nullable=False, default="draft")
    created_by_user_id: Mapped[str | None] = mapped_column("CreatedByUserId", String(32), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)
    is_next_action: Mapped[bool] = mapped_column("IsNextAction", Boolean, nullable=False, default=False)
    # JSON-encoded list of {name, content_type, content_bytes (base64), size_bytes}.
    # Capped by the 25 MB attachment policy enforced at send time, so the
    # column stays small enough for NVARCHAR(MAX).
    attachments: Mapped[str | None] = mapped_column("Attachments", UnicodeText, nullable=True)


class CXSentEmail(Base):
    """Emails sent from Salezilla via MS Graph."""

    __tablename__ = "CX_SentEmails"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    contact_id: Mapped[str | None] = mapped_column("ContactId", String(32), nullable=True)
    account_id: Mapped[str | None] = mapped_column("AccountId", String(32), nullable=True)
    draft_id: Mapped[int | None] = mapped_column("DraftId", Integer, nullable=True)
    from_email: Mapped[str] = mapped_column("FromEmail", String(256), nullable=False)
    from_name: Mapped[str | None] = mapped_column("FromName", Unicode(128), nullable=True)
    to_email: Mapped[str] = mapped_column("ToEmail", String(256), nullable=False)
    to_name: Mapped[str | None] = mapped_column("ToName", Unicode(128), nullable=True)
    cc_emails: Mapped[str | None] = mapped_column("CcEmails", UnicodeText, nullable=True)
    bcc_emails: Mapped[str | None] = mapped_column("BccEmails", UnicodeText, nullable=True)
    subject: Mapped[str] = mapped_column("Subject", Unicode(512), nullable=False)
    body: Mapped[str] = mapped_column("Body", UnicodeText, nullable=False)
    thread_id: Mapped[str | None] = mapped_column("ThreadId", String(512), nullable=True)
    internet_message_id: Mapped[str | None] = mapped_column("InternetMessageId", String(512), nullable=True)
    sent_by_user_id: Mapped[str | None] = mapped_column("SentByUserId", String(32), nullable=True)
    sent_time: Mapped[datetime] = mapped_column("SentTime", DateTime, nullable=False)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXNote(Base):
    """Free-text notes on Potentials."""

    __tablename__ = "CX_Notes"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    content: Mapped[str] = mapped_column("Content", UnicodeText, nullable=False)
    created_by_user_id: Mapped[str | None] = mapped_column("CreatedByUserId", String(32), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXTodo(Base):
    """Action items per Potential. Can be user-created or agent-reconciled."""

    __tablename__ = "CX_Todos"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    text: Mapped[str] = mapped_column("Text", Unicode(512), nullable=False)
    status: Mapped[str] = mapped_column("Status", String(20), nullable=False, default="pending")
    is_completed: Mapped[bool] = mapped_column("IsCompleted", Boolean, nullable=False, default=False)
    # "user" | "agent" — user-edited agent rows get flipped to "user" so the
    # reconcile agent stops touching them.
    source: Mapped[str] = mapped_column("Source", String(16), nullable=False, default="user")
    created_by_user_id: Mapped[str | None] = mapped_column("CreatedByUserId", String(32), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXFile(Base):
    """File attachments on Potentials."""

    __tablename__ = "CX_Files"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    file_name: Mapped[str] = mapped_column("FileName", Unicode(256), nullable=False)
    mime_type: Mapped[str | None] = mapped_column("MimeType", String(128), nullable=True)
    file_size: Mapped[int | None] = mapped_column("FileSize", Integer, nullable=True)
    storage_path: Mapped[str] = mapped_column("StoragePath", Unicode(512), nullable=False)
    created_by_user_id: Mapped[str | None] = mapped_column("CreatedByUserId", String(32), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXCallLog(Base):
    """Phone call records — linked to Twilio calls for recording + transcript."""

    __tablename__ = "CX_CallLogs"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    contact_id: Mapped[str | None] = mapped_column("ContactId", String(32), nullable=True)
    account_id: Mapped[str | None] = mapped_column("AccountId", String(32), nullable=True)
    phone_number: Mapped[str | None] = mapped_column("PhoneNumber", String(32), nullable=True)
    contact_name: Mapped[str | None] = mapped_column("ContactName", Unicode(128), nullable=True)
    duration: Mapped[int] = mapped_column("Duration", Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column("Status", String(16), nullable=False, default="completed")
    notes: Mapped[str | None] = mapped_column("Notes", UnicodeText, nullable=True)
    called_by_user_id: Mapped[str | None] = mapped_column("CalledByUserId", String(32), nullable=True)
    twilio_call_sid: Mapped[str | None] = mapped_column("TwilioCallSid", String(64), nullable=True)
    recording_url: Mapped[str | None] = mapped_column("RecordingUrl", Unicode(512), nullable=True)
    recording_file_id: Mapped[int | None] = mapped_column("RecordingFileId", Integer, nullable=True)
    transcript: Mapped[str | None] = mapped_column("Transcript", UnicodeText, nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXActivity(Base):
    """Timeline / audit log."""

    __tablename__ = "CX_Activities"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    contact_id: Mapped[str | None] = mapped_column("ContactId", String(32), nullable=True)
    account_id: Mapped[str | None] = mapped_column("AccountId", String(32), nullable=True)
    activity_type: Mapped[str] = mapped_column("ActivityType", String(32), nullable=False)
    description: Mapped[str | None] = mapped_column("Description", UnicodeText, nullable=True)
    performed_by_user_id: Mapped[str | None] = mapped_column("PerformedByUserId", String(32), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXChatMessage(Base):
    """AI chat conversation history."""

    __tablename__ = "CX_ChatMessages"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column("UserId", String(32), nullable=False)
    potential_id: Mapped[str | None] = mapped_column("PotentialId", String(16), nullable=True)  # 7-digit potential_number
    role: Mapped[str] = mapped_column("Role", String(16), nullable=False)
    content: Mapped[str] = mapped_column("Content", UnicodeText, nullable=False)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)



class CXGlobalChatConversation(Base):
    """Global AI chat — one row per conversation thread per user."""

    __tablename__ = "CX_GlobalChatConversations"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column("UserId", String(32), nullable=False)
    title: Mapped[str | None] = mapped_column("Title", Unicode(256), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXGlobalChatMessage(Base):
    """Global AI chat history — cross-entity questions, not tied to any single Potential."""

    __tablename__ = "CX_GlobalChatMessages"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column("UserId", String(32), nullable=False)
    conversation_id: Mapped[int | None] = mapped_column("ConversationId", Integer, nullable=True)
    role: Mapped[str] = mapped_column("Role", String(16), nullable=False)
    content: Mapped[str] = mapped_column("Content", UnicodeText, nullable=False)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXMeeting(Base):
    """Meetings synced from MS Calendar."""

    __tablename__ = "CX_Meetings"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    ms_event_id: Mapped[str] = mapped_column("MSEventId", String(256), nullable=False)
    potential_id: Mapped[str | None] = mapped_column("PotentialId", String(32), nullable=True)
    contact_id: Mapped[str | None] = mapped_column("ContactId", String(32), nullable=True)
    account_id: Mapped[str | None] = mapped_column("AccountId", String(32), nullable=True)
    title: Mapped[str] = mapped_column("Title", Unicode(256), nullable=False)
    start_time: Mapped[datetime] = mapped_column("StartTime", DateTime, nullable=False)
    end_time: Mapped[datetime | None] = mapped_column("EndTime", DateTime, nullable=True)
    location: Mapped[str | None] = mapped_column("Location", Unicode(256), nullable=True)
    description: Mapped[str | None] = mapped_column("Description", UnicodeText, nullable=True)
    meeting_link: Mapped[str | None] = mapped_column("MeetingLink", String(1024), nullable=True)
    meeting_type: Mapped[str | None] = mapped_column("MeetingType", String(32), nullable=True)
    attendees: Mapped[str | None] = mapped_column("Attendees", UnicodeText, nullable=True)
    user_id: Mapped[str] = mapped_column("UserId", String(32), nullable=False)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)
    is_active: Mapped[bool] = mapped_column("IsActive", Boolean, nullable=False, default=True)


class CXFollowUpSchedule(Base):
    """One row per scheduled follow-up tick (D3/D5/D8/D12)."""

    __tablename__ = "CX_FollowUpSchedule"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    potential_number: Mapped[str] = mapped_column("PotentialNumber", String(20), nullable=False)
    trigger_message_id: Mapped[str | None] = mapped_column("TriggerMessageId", String(512), nullable=True)
    trigger_sent_time: Mapped[datetime] = mapped_column("TriggerSentTime", DateTime, nullable=False)
    day_offset: Mapped[int] = mapped_column("DayOffset", Integer, nullable=False)
    scheduled_time: Mapped[datetime] = mapped_column("ScheduledTime", DateTime, nullable=False)
    status: Mapped[str] = mapped_column("Status", String(20), nullable=False, default="pending")
    fired_time: Mapped[datetime | None] = mapped_column("FiredTime", DateTime, nullable=True)
    insight_id: Mapped[int | None] = mapped_column("InsightId", Integer, nullable=True)
    cancel_reason: Mapped[str | None] = mapped_column("CancelReason", String(50), nullable=True)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)


class CXAgentDraftHistory(Base):
    """Append-only audit log — snapshots agent draft content before it gets
    overwritten (upsert) or resolved (skip/done/sent)."""

    __tablename__ = "CX_AgentDraftHistory"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(20), nullable=False)
    agent_id: Mapped[str] = mapped_column("AgentId", String(64), nullable=False)
    agent_name: Mapped[str | None] = mapped_column("AgentName", Unicode(128), nullable=True)
    trigger_category: Mapped[str | None] = mapped_column("TriggerCategory", String(32), nullable=True)
    content: Mapped[str | None] = mapped_column("Content", UnicodeText, nullable=True)
    status: Mapped[str] = mapped_column("Status", String(16), nullable=False)
    resolution: Mapped[str | None] = mapped_column("Resolution", String(16), nullable=True)
    triggered_at: Mapped[datetime | None] = mapped_column("TriggeredAt", DateTime, nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column("CompletedAt", DateTime, nullable=True)
    resolved_at: Mapped[datetime] = mapped_column("ResolvedAt", DateTime, nullable=False)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)


class CXDraftAttachment(Base):
    """Agent-generated email attachments (typically HTML) for draft emails.

    Created by the attachment agent's webhook. The HTML body is stored in GCS;
    this table holds the metadata. The UI shows a removable chip in the
    NextAction composer; the send endpoint downloads from GCS and attaches
    base64-encoded to the Graph send payload.
    """

    __tablename__ = "CX_DraftAttachments"

    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True, autoincrement=True)
    potential_id: Mapped[str] = mapped_column("PotentialId", String(32), nullable=False)
    agent_id: Mapped[str | None] = mapped_column("AgentId", String(64), nullable=True)
    gcs_path: Mapped[str] = mapped_column("GcsPath", Unicode(512), nullable=False)
    filename: Mapped[str] = mapped_column("Filename", Unicode(256), nullable=False)
    content_type: Mapped[str] = mapped_column("ContentType", String(64), nullable=False, default="text/html")
    file_size: Mapped[int | None] = mapped_column("FileSize", Integer, nullable=True)
    is_removed: Mapped[bool] = mapped_column("IsRemoved", Boolean, nullable=False, default=False)
    is_sent: Mapped[bool] = mapped_column("IsSent", Boolean, nullable=False, default=False)
    created_time: Mapped[datetime] = mapped_column("CreatedTime", DateTime, nullable=False)
    updated_time: Mapped[datetime] = mapped_column("UpdatedTime", DateTime, nullable=False)


class LookupService(Base):
    __tablename__ = "service"
    id: Mapped[int] = mapped_column("Id", Integer, primary_key=True)
    service: Mapped[str] = mapped_column("Service", String(128), nullable=False)
    active: Mapped[int] = mapped_column("Active", Integer, nullable=False)


class LookupSubservice(Base):
    __tablename__ = "Subservices"
    id: Mapped[int] = mapped_column("ID", Integer, primary_key=True)
    name: Mapped[str] = mapped_column("Name", String(256), nullable=False)
    service_id: Mapped[int] = mapped_column("ServiceID", Integer, nullable=False)


class LookupPotentialStage(Base):
    __tablename__ = "potentialstageid"
    stage_id: Mapped[str] = mapped_column("StageID", String(32), primary_key=True)
    stage_name: Mapped[str] = mapped_column("StageName", String(128), nullable=False)
